from flask  import request, jsonify

from . import receipt_processor


#In memory data store for the request with unique id which is generated by below code
data_store = {}


@receipt_processor.route('/process', method=["POST"])
def process_receipt_for_id():
    data = request.get_json()
    if not data:
        return jsonify({"error": "Invalid JSON data"}), 400

    