from flask  import request, jsonify
from pydantic import BaseModel, ValidationError
from . import receipt_processor_api

from receipt_processor.data_validation import Receipt, Item
import uuid

#In memory data store for the request with unique id which is generated by below code
receipts = {}


@receipt_processor_api.route('/process', method=["POST"])
def process_receipt_for_id():
    data = request.get_json()
    try:
        receipt = Receipt(**data)
    except ValidationError as e:
        return jsonify({"error": str(e)}), 400
    
    receipt_id = str(uuid.uuid4())
    receipts[receipt_id] = receipt.model_dump()
    return jsonify({"id": receipt_id}), 200




    